apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80          # Port bên ngoài
      targetPort: 8080  # Port trong container
  type: LoadBalancer  # Hoặc ClusterIP nếu chỉ dùng nội bộ
